version: "2"
services:
  secureblog:
    build:
      context: secureblog
    environment:
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=blog123!
      - POSTGRES_HOST=db
    depends_on:
      - db
    restart: always
    networks:
      webeve_net:
        ipv4_address: 172.18.0.4

  db:
    build:
      context: db
    environment:
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=blog123!
    networks:
      webeve_net:
        ipv4_address: 172.18.0.2
  
  securebloglanding:
    build:
      context: securebloglanding
    restart: always
    networks:
      webeve_net:
        ipv4_address: 172.18.0.5

  evilsite:
    build:
      context: evilsite
    networks:
      webeve_net:
        ipv4_address: 172.18.0.3

networks:
  webeve_net:
    driver: bridge
    ipam:
      config:
       - subnet: 172.18.0.0/24 
         gateway: 172.18.0.1