version: "2"
services:
  secureblog:
    build:
      context: secureblog
    environment:
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=blog123!
      - POSTGRES_HOST=db
    depends_on:
      - db
    ports:
      - "8080:5000"
    restart: always

  db:
    build:
      context: db
    environment:
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=blog123!

  evilsite:
    build:
      context: evilsite
    ports:
      - "666:5000"
